
frontURI: "http://localhost:3000"

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true


spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/board_vue?useSSL=false&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: yeonho5376!

  output:
    ansi:
      enabled: always

  properties:
    hibernate:
      default_batch_fetch_size: 50

  jpa:
    database: mysql
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
    jackson:
      serialization:
        fail-on-empty-beans: false

  devtools:
    livereload:
      enabled: true
    restart:
      enable: true
